# Change these first
owner: hbwebpages # Your GitHub username
repo: enabizuptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Enabiz
    url: https://www.enabiz.gov.tr

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /enabizuptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Enabiz Status Page
  introTitle: "**Enabiz** Uptime"
  introMessage: Enabiz Uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
